In [7]:
!pip install nltk --user

You should consider upgrading via the 'C:\Users\Vishal Kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [10]:
import sys
!{sys.executable} -m pip install nltk

'C:\Users\Vishal' is not recognized as an internal or external command,
operable program or batch file.


In [12]:
import sys
!"{sys.executable}" -m pip install nltk

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 24.1 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\Vishal Kumar\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [13]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
import nltk
from nltk.tokenize import word_tokenize

In [14]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [16]:
# Tokenization
nltk.download('punkt') #To tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\Vishal
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to C:\Users\Vishal
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

## Tokenize

In [18]:
tokens=word_tokenize(document.lower()) #seperate the words
tokens

['about',
 'the',
 'program',
 'what',
 'is',
 'the',
 'course',
 'fee',
 'for',
 'data',
 'science',
 'mentorship',
 'program',
 '(',
 'dsmp',
 '2023',
 ')',
 'the',
 'course',
 'follows',
 'a',
 'monthly',
 'subscription',
 'model',
 'where',
 'you',
 'have',
 'to',
 'make',
 'monthly',
 'payments',
 'of',
 'rs',
 '799/month',
 '.',
 'what',
 'is',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 '?',
 'the',
 'total',
 'duration',
 'of',
 'the',
 'course',
 'is',
 '7',
 'months',
 '.',
 'so',
 'the',
 'total',
 'course',
 'fee',
 'becomes',
 '799',
 '*',
 '7',
 '=',
 'rs',
 '5600',
 '(',
 'approx',
 '.',
 ')',
 'what',
 'is',
 'the',
 'syllabus',
 'of',
 'the',
 'mentorship',
 'program',
 '?',
 'we',
 'will',
 'be',
 'covering',
 'the',
 'following',
 'modules',
 ':',
 'python',
 'fundamentals',
 'python',
 'libraries',
 'for',
 'data',
 'science',
 'data',
 'analysis',
 'sql',
 'for',
 'data',
 'science',
 'maths',
 'for',
 'machine',
 'learning',
 'ml',
 'algorithms',
 'p

In [19]:
Counter(tokens) #No of times word occur 

Counter({'the': 69,
         'you': 37,
         '.': 32,
         '?': 30,
         'i': 28,
         'to': 27,
         'a': 19,
         'of': 19,
         'is': 18,
         'have': 18,
         ',': 18,
         'will': 16,
         'can': 15,
         'what': 14,
         'course': 12,
         'program': 11,
         'for': 10,
         'all': 9,
         'sessions': 9,
         'in': 9,
         'on': 9,
         'be': 8,
         'and': 8,
         'this': 8,
         'if': 8,
         'am': 8,
         'make': 7,
         'we': 7,
         'do': 7,
         'payment': 7,
         'pay': 7,
         'subscription': 6,
         'where': 6,
         'rs': 6,
         'so': 6,
         'session': 6,
         'our': 6,
         'paid': 6,
         'able': 6,
         'your': 6,
         'website': 6,
         'placement': 6,
         'fee': 5,
         'monthly': 5,
         ':': 5,
         'not': 5,
         'get': 5,
         'yes': 5,
         'once': 5,
         'join': 5,
  

In [20]:
Counter(tokens).keys() #Unique words

dict_keys(['about', 'the', 'program', 'what', 'is', 'course', 'fee', 'for', 'data', 'science', 'mentorship', '(', 'dsmp', '2023', ')', 'follows', 'a', 'monthly', 'subscription', 'model', 'where', 'you', 'have', 'to', 'make', 'payments', 'of', 'rs', '799/month', '.', 'total', 'duration', '?', '7', 'months', 'so', 'becomes', '799', '*', '=', '5600', 'approx', 'syllabus', 'we', 'will', 'be', 'covering', 'following', 'modules', ':', 'python', 'fundamentals', 'libraries', 'analysis', 'sql', 'maths', 'machine', 'learning', 'ml', 'algorithms', 'practical', 'mlops', 'case', 'studies', 'can', 'check', 'detailed', 'here', '-', 'https', '//learnwith.campusx.in/courses/campusx-data-science-mentorship-program-637339afe4b0615a1bbed390', 'deep', 'and', 'nlp', 'part', 'this', 'no', ',', 'both', 'are', 'not', '’', 's', 'curriculum', 'if', 'i', 'miss', 'live', 'session', 'get', 'recording', 'yes', 'all', 'our', 'sessions', 'recorded', 'even', 'go', 'back', 'watch', 'find', 'class', 'schedule', 'checkout

## Build vocab

In [29]:
vocab={'<unk>':0}

for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]=len(vocab)

vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [30]:
len(vocab)

289

In [31]:
document.split('\n')[0] #gives the sentences

'About the Program'

In [32]:
input_sentences=document.split('\n')
input_sentences

['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [33]:
for sentence in input_sentences:
    print(word_tokenize(sentence.lower()))

['about', 'the', 'program']
['what', 'is', 'the', 'course', 'fee', 'for', 'data', 'science', 'mentorship', 'program', '(', 'dsmp', '2023', ')']
['the', 'course', 'follows', 'a', 'monthly', 'subscription', 'model', 'where', 'you', 'have', 'to', 'make', 'monthly', 'payments', 'of', 'rs', '799/month', '.']
['what', 'is', 'the', 'total', 'duration', 'of', 'the', 'course', '?']
['the', 'total', 'duration', 'of', 'the', 'course', 'is', '7', 'months', '.', 'so', 'the', 'total', 'course', 'fee', 'becomes', '799', '*', '7', '=', 'rs', '5600', '(', 'approx', '.', ')']
['what', 'is', 'the', 'syllabus', 'of', 'the', 'mentorship', 'program', '?']
['we', 'will', 'be', 'covering', 'the', 'following', 'modules', ':']
['python', 'fundamentals']
['python', 'libraries', 'for', 'data', 'science']
['data', 'analysis']
['sql', 'for', 'data', 'science']
['maths', 'for', 'machine', 'learning']
['ml', 'algorithms']
['practical', 'ml']
['mlops']
['case', 'studies']
['you', 'can', 'check', 'the', 'detailed', 'sy

In [34]:
def text_to_indices(sentence,vocab):
    numerical_sentence=[]
    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab['<unk>'])

    return numerical_sentence

In [37]:
for sentence in input_sentences:
    print(text_to_indices(word_tokenize(sentence.lower()),vocab))
    break #1st sentence

[1, 2, 3]


In [39]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [40]:
input_numerical_sentences

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30],
 [4, 5, 2, 31, 32, 27, 2, 6, 33],
 [2,
  31,
  32,
  27,
  2,
  6,
  5,
  34,
  35,
  30,
  36,
  2,
  31,
  6,
  7,
  37,
  38,
  39,
  34,
  40,
  28,
  41,
  12,
  42,
  30,
  15],
 [4, 5, 2, 43, 27, 2, 11, 3, 33],
 [44, 45, 46, 47, 2, 48, 49, 50],
 [51, 52],
 [51, 53, 8, 9, 10],
 [9, 54],
 [55, 8, 9, 10],
 [56, 8, 57, 58],
 [59, 60],
 [61, 59],
 [62],
 [63, 64],
 [22, 65, 66, 2, 67, 43, 68, 69, 70, 50, 71],
 [45, 72, 58, 73, 74, 46, 17, 75, 27, 76, 3, 33],
 [77, 78, 74, 73, 72, 58, 79, 80, 81, 17, 75, 27, 76, 3, 82, 83, 84, 30],
 [4, 85, 86, 87, 17, 88, 89, 33, 45, 86, 90, 17, 91, 27, 2, 89, 33],
 [92,
  93,
  94,
  95,
  80,
  96,
  78,
  36,
  97,
  85,
  22,
  87,
  17,
  89,
  22,
  65,
  98,
  99,
  73,
  100,
  2,
  91,
  30],
 [21, 65, 86, 101, 2, 102, 103, 33],
 [104,
  76,
  105,
  106,
  24,
  107,
  108,
  109,
  108,
  110,
  111,
  27,

In [41]:
len(input_numerical_sentences)

78

In [43]:
for sentence in input_numerical_sentences:
    for i in range(1,len(sentence)):
        print(sentence[:i+1])
    break

[1, 2]
[1, 2, 3]


In [44]:
for sentence in input_numerical_sentences:
    for i in range(1,len(sentence)):
        print(sentence[:i+1])

[1, 2]
[1, 2, 3]
[4, 5]
[4, 5, 2]
[4, 5, 2, 6]
[4, 5, 2, 6, 7]
[4, 5, 2, 6, 7, 8]
[4, 5, 2, 6, 7, 8, 9]
[4, 5, 2, 6, 7, 8, 9, 10]
[4, 5, 2, 6, 7, 8, 9, 10, 11]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14]
[4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15]
[2, 6]
[2, 6, 16]
[2, 6, 16, 17]
[2, 6, 16, 17, 18]
[2, 6, 16, 17, 18, 19]
[2, 6, 16, 17, 18, 19, 20]
[2, 6, 16, 17, 18, 19, 20, 21]
[2, 6, 16, 17, 18, 19, 20, 21, 22]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29]
[2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 

In [45]:
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [46]:
len(training_sequence)

942

In [47]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [49]:
len_list = [] #padding to same the input 

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [50]:
training_sequence[0]

[1, 2]

In [51]:
for sequence in training_sequence:

  print([0]*(max(len_list) - len(sequence)) + sequence)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 2]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5, 2, 6]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [52]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [53]:
len(padded_training_sequence)

942

In [54]:
padded_training_sequence[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2]

In [55]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [56]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [57]:
padded_training_sequence.shape

torch.Size([942, 62])

In [58]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [59]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [60]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [61]:
class custondataset(Dataset):
    def __init__(self,X,y):
        self.X=X
        self.y=y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self,idx):
        return self.X[idx],self.y[idx]

In [62]:
dataset=custondataset(X,y)

In [63]:
len(dataset)

942

In [64]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)

In [65]:
class LSTMModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [84]:
a=nn.Embedding(289, 100)
b=nn.LSTM(100, 150, batch_first=True)

In [97]:
c=dataset[0][0].unsqueeze(0)
c

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [98]:
c.shape

torch.Size([1, 61])

In [99]:
c.unsqueeze(0).shape

torch.Size([1, 1, 61])

In [101]:
d=a(c)

In [100]:
a(c).shape

torch.Size([1, 61, 100])

In [102]:
d

tensor([[[-0.1138,  0.1525, -2.1687,  ..., -1.2872,  0.8059, -1.4586],
         [-0.1138,  0.1525, -2.1687,  ..., -1.2872,  0.8059, -1.4586],
         [-0.1138,  0.1525, -2.1687,  ..., -1.2872,  0.8059, -1.4586],
         ...,
         [-0.1138,  0.1525, -2.1687,  ..., -1.2872,  0.8059, -1.4586],
         [-0.1138,  0.1525, -2.1687,  ..., -1.2872,  0.8059, -1.4586],
         [-0.0483,  0.9411, -1.2230,  ...,  1.2741,  0.9308,  1.0762]]],
       grad_fn=<EmbeddingBackward0>)

In [106]:
e,f=b(d)
e

tensor([[[ 0.0939,  0.0883,  0.0409,  ..., -0.0416,  0.0532,  0.0491],
         [ 0.1545,  0.1101,  0.0562,  ..., -0.0660,  0.0651,  0.0398],
         [ 0.1944,  0.1165,  0.0561,  ..., -0.0811,  0.0614,  0.0267],
         ...,
         [ 0.2579,  0.1349,  0.0312,  ..., -0.1132,  0.0191,  0.0125],
         [ 0.2579,  0.1349,  0.0312,  ..., -0.1132,  0.0191,  0.0125],
         [ 0.0552,  0.2510, -0.0015,  ..., -0.0835, -0.1136,  0.2729]]],
       grad_fn=<TransposeBackward0>)

In [107]:
len(e)

1

In [108]:
e.shape #set of all intermediate hidden state

torch.Size([1, 61, 150])

In [111]:
f

(tensor([[[ 0.0552,  0.2510, -0.0015,  0.1966, -0.0633, -0.0426,  0.0286,
            0.0890, -0.0464, -0.2386, -0.0107, -0.0367, -0.1610, -0.0989,
            0.1068,  0.0485, -0.0239,  0.1626, -0.0242,  0.3413,  0.0563,
            0.1815, -0.1141, -0.0674, -0.1884, -0.2040,  0.1732,  0.0548,
            0.0436,  0.0082, -0.1067,  0.2862, -0.0357, -0.0281, -0.0480,
            0.0104, -0.1480,  0.2101, -0.1830, -0.0072,  0.0440, -0.0365,
            0.0759, -0.1184, -0.1734,  0.0553, -0.0408, -0.0321, -0.0790,
            0.0225,  0.1727, -0.0106,  0.3437,  0.3119,  0.0979,  0.0138,
            0.0768,  0.0759, -0.1381,  0.1346, -0.0337,  0.2472, -0.0645,
            0.0414, -0.2232, -0.0762,  0.0390,  0.0448,  0.0956,  0.0934,
            0.0584, -0.3069,  0.1320,  0.2364,  0.0852, -0.1295,  0.1529,
           -0.1063,  0.0146,  0.0283,  0.0197, -0.0327,  0.1094,  0.1997,
            0.0333, -0.1211,  0.0870,  0.0404,  0.0878, -0.1408,  0.0925,
            0.0640, -0.0717, -0.2396, 

In [112]:
len(f)

2

In [113]:
g,h=f

In [114]:
g.shape #final hidden state

torch.Size([1, 1, 150])

In [115]:
h.shape #final cell state

torch.Size([1, 1, 150])

In [116]:
z=nn.Linear(150, 289)
z

Linear(in_features=150, out_features=289, bias=True)

In [117]:
z(g)

tensor([[[-0.0187, -0.0442,  0.0136,  0.1227, -0.0017, -0.0543, -0.0638,
          -0.0712, -0.1272, -0.1124,  0.0737,  0.0360,  0.0328,  0.0671,
          -0.2906, -0.0726,  0.1654, -0.0794, -0.0727, -0.0634,  0.0183,
          -0.1703,  0.0122, -0.0126, -0.0284, -0.0460,  0.1200, -0.0089,
          -0.0616, -0.0802,  0.0105, -0.0765,  0.0493,  0.1104, -0.0037,
          -0.0426, -0.0124,  0.0760, -0.0047, -0.0025, -0.0029, -0.1009,
          -0.0699, -0.2469, -0.0671, -0.1370,  0.0073,  0.0821, -0.1077,
          -0.0324,  0.0234,  0.0800,  0.0521,  0.1196,  0.0176,  0.1243,
          -0.0947,  0.1052,  0.0816, -0.1177,  0.0919,  0.0310,  0.0249,
           0.0078,  0.0319, -0.0561,  0.0090,  0.0089, -0.0119,  0.0347,
          -0.1288,  0.1315, -0.0484, -0.0334,  0.0038, -0.1046, -0.0494,
           0.0589, -0.1131, -0.0516, -0.0836,  0.0038,  0.0627,  0.0607,
          -0.0381,  0.0085,  0.0992, -0.1002, -0.0232,  0.0210, -0.0688,
           0.1149, -0.0729,  0.0562,  0.1039,  0.04

In [118]:
z(g).shape

torch.Size([1, 1, 289])

In [119]:
z(h)

tensor([[[ 0.0398,  0.0033, -0.0058,  0.2799,  0.0776, -0.0609, -0.1658,
          -0.1308, -0.1051, -0.3438,  0.0222,  0.1138,  0.0024,  0.0785,
          -0.5885, -0.0855,  0.2018, -0.1871, -0.1866, -0.0386, -0.0992,
          -0.3237,  0.0920,  0.0558, -0.0371,  0.0438,  0.1210,  0.0883,
          -0.1202, -0.1981,  0.0916, -0.0705,  0.0359,  0.2626,  0.0220,
          -0.1492, -0.0540,  0.1003,  0.0389, -0.0184, -0.0774, -0.0896,
          -0.1618, -0.3810, -0.0948, -0.2524, -0.0091,  0.1273, -0.2895,
           0.0629,  0.0537,  0.1757,  0.1212,  0.1616,  0.0908,  0.2072,
          -0.2280,  0.2800,  0.2846, -0.2096,  0.1666,  0.1077, -0.0746,
           0.0294,  0.0270,  0.0496,  0.0263,  0.0172,  0.0228,  0.0129,
          -0.1603,  0.2353, -0.0506, -0.0995, -0.0906, -0.2244, -0.0622,
           0.1001, -0.2030, -0.0596, -0.0899,  0.0516,  0.1692,  0.0605,
           0.0337, -0.0070,  0.1673, -0.0687, -0.0366,  0.0015, -0.0351,
           0.1923, -0.2341,  0.1928,  0.1847,  0.13

In [120]:
z(h).squeeze(0).shape

torch.Size([1, 289])

In [121]:
model = LSTMModel(len(vocab))

In [122]:
model

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [123]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [124]:
# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 166.1775
Epoch: 2, Loss: 146.2984
Epoch: 3, Loss: 134.0484
Epoch: 4, Loss: 121.2951
Epoch: 5, Loss: 109.6028
Epoch: 6, Loss: 98.0385
Epoch: 7, Loss: 87.1672
Epoch: 8, Loss: 77.9472
Epoch: 9, Loss: 68.7635
Epoch: 10, Loss: 60.9265
Epoch: 11, Loss: 53.5131
Epoch: 12, Loss: 46.8757
Epoch: 13, Loss: 41.5944
Epoch: 14, Loss: 36.6022
Epoch: 15, Loss: 32.1633
Epoch: 16, Loss: 28.3539
Epoch: 17, Loss: 25.0290
Epoch: 18, Loss: 22.2667
Epoch: 19, Loss: 19.7275
Epoch: 20, Loss: 17.6722
Epoch: 21, Loss: 15.8595
Epoch: 22, Loss: 14.3731
Epoch: 23, Loss: 13.0353
Epoch: 24, Loss: 11.9990
Epoch: 25, Loss: 10.8969
Epoch: 26, Loss: 10.1817
Epoch: 27, Loss: 9.6047
Epoch: 28, Loss: 8.9873
Epoch: 29, Loss: 8.2817
Epoch: 30, Loss: 7.8810
Epoch: 31, Loss: 7.6648
Epoch: 32, Loss: 7.1316
Epoch: 33, Loss: 6.9941
Epoch: 34, Loss: 6.5622
Epoch: 35, Loss: 6.3621
Epoch: 36, Loss: 6.1187
Epoch: 37, Loss: 6.0092
Epoch: 38, Loss: 5.8427
Epoch: 39, Loss: 5.6685
Epoch: 40, Loss: 5.4204
Epoch: 41, Loss: 5

In [125]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]


In [126]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly subscription'

In [127]:
import time

num_tokens = 10
input_text = "hi how are"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

hi how are 2
hi how are 2 criterias
hi how are 2 criterias :
hi how are 2 criterias : is
hi how are 2 criterias : is the
hi how are 2 criterias : is the course
hi how are 2 criterias : is the course assessments
hi how are 2 criterias : is the course assessments .
hi how are 2 criterias : is the course assessments . so
hi how are 2 criterias : is the course assessments . so the


In [128]:
dataloader1 = DataLoader(dataset, batch_size=32, shuffle=False)

In [131]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader1:
            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader)
print(f"Model Accuracy: {accuracy:.2f}%")

Model Accuracy: 95.65%
